fenced/fence.py
fenced/logging.py
fenced/main.py

- use middlewared client to generate a list of disks detected on the system
- add `--use-zpools`, `-uz` arguments to provide the ability to reserve the disks in use by the detected zpools

NAS-109649 / 21.04 / add ability to reserve disks based off detected zpool(s)

---

debian/changelog
fenced/fence.py
setup.py

I can't depend on `/etc/hostid` being unique between controllers on an HA system. At least, not when SCALE is installed as a VM on a bhyve host. The `/etc/hostid`'s are the same between the VMs which breaks this program at a fundamental level.

NAS-116071 / 22.12 / use /etc/machine-id instead of /etc/hostid

---

debian/changelog
fenced/fence.py
setup.py

I can't depend on /etc/hostid being unique between controllers on an HA system. At least, not when SCALE is installed as a VM on a bhyve host. The /etc/hostid's are the same between the VMs which breaks this program at a fundamental level.

NAS-116071 / 22.02.4 / use /etc/machine-id instead of /etc/hostid

---

debian/changelog
fenced/fence.py
setup.py

I can't depend on /etc/hostid being unique between controllers on an HA system. At least, not when SCALE is installed as a VM on a bhyve host. The /etc/hostid's are the same between the VMs which breaks this program at a fundamental level.

NAS-116071 / 22.02.3 / use /etc/machine-id instead of /etc/hostid

---

fenced/fence.py
fenced/utils.py

Fenced managed to not enumerate disks using middlewared client. That's concerning, so I've added a ton more functions to try and enumerate disks. The idea is that if we fail to enumerate disks again, it will be very, very obvious that something is critically wrong with the system.

more fault tolerance for enumerating disks

---

fenced/disks.py

The logic by which we check if the reservation is "owned"
by this host is custom logic that was written by us and is
flawed. The spec for handling pr keys defines a command
that can be used to determine if this host is the current
reservation holder. Since we don't have this, we check
for reservation conflict and try to "update" the key since
getting a reservation conflict when trying to preempt the
current key typically means this host is the current owner

NAS-127630 / 24.10 / handle edge-case error on preemption

---

fenced/disks.py

The logic by which we check if the reservation is "owned"
by this host is custom logic that was written by us and is
flawed. The spec for handling pr keys defines a command
that can be used to determine if this host is the current
reservation holder. Since we don't have this, we check
for reservation conflict and try to "update" the key since
getting a reservation conflict when trying to preempt the
current key typically means this host is the current owner
Original PR: https://github.com/truenas/py-fenced/pull/41
Jira URL: https://ixsystems.atlassian.net/browse/NAS-127630

NAS-127630 / 24.04.0 / handle edge-case error on preemption (by yocalebo)

---

fenced/disks.py

The logic by which we check if the reservation is "owned"
by this host is custom logic that was written by us and is
flawed. The spec for handling pr keys defines a command
that can be used to determine if this host is the current
reservation holder. Since we don't have this, we check
for reservation conflict and try to "update" the key since
getting a reservation conflict when trying to preempt the
current key typically means this host is the current owner
Original PR: https://github.com/truenas/py-fenced/pull/41
Jira URL: https://ixsystems.atlassian.net/browse/NAS-127630

NAS-127630 / 24.04-RC.1 / handle edge-case error on preemption (by yocalebo)

---

fenced/utils.py

NAS-131361 / 25.04 / more resilient disk enumeration

---

fenced/utils.py

Automatic cherry-pick failed. Please resolve conflicts by running:
git cherry-pick -x 007a9b8e1f54bb9b9f7ca7d75d49e7e7d9d15f1c
If the original PR was merged via a squash, you can just cherry-pick the squashed commit:
git reset --hard HEAD~1
git cherry-pick -x cbf59f23235f4ec386e4f1956a75f1f2278ec8e0
#
Original PR: https://github.com/truenas/py-fenced/pull/46
Jira URL: https://ixsystems.atlassian.net/browse/NAS-131361

NAS-131361 / 24.04.2.3 / more resilient disk enumeration (by yocalebo)

---

fenced/utils.py

#
Original PR: https://github.com/truenas/py-fenced/pull/46
Jira URL: https://ixsystems.atlassian.net/browse/NAS-131361

NAS-131361 / 24.10.0 / more resilient disk enumeration (by yocalebo)

---

fenced/utils.py

The most recent changes here added a 2nd attempt at enumerating disks to work-around a particular situation we're seeing for a particular shelf in the field. The problem, is that the skip logic was inverted so the 2nd attempt actually produced 0 disks.
Because of this issue, the particular problem it set out to solve was rendered useless because the 2nd attempt should be producing MORE disks than the 1st attempt (again problem a particular shelf). This fixes that regression by removing the dict comprehension and doing a good ole fashioned for loop.

NAS-131395 / 25.04 / fix subtle regression in fenced

---

fenced/utils.py

The most recent changes here added a 2nd attempt at enumerating disks to work-around a particular situation we're seeing for a particular shelf in the field. The problem, is that the skip logic was inverted so the 2nd attempt actually produced 0 disks.
Because of this issue, the particular problem it set out to solve was rendered useless because the 2nd attempt should be producing MORE disks than the 1st attempt (again problem a particular shelf). This fixes that regression by removing the dict comprehension and doing a good ole fashioned for loop.
Original PR: https://github.com/truenas/py-fenced/pull/51
Jira URL: https://ixsystems.atlassian.net/browse/NAS-131395

NAS-131395 / 24.04.2.3 / fix subtle regression in fenced (by yocalebo)

---

fenced/utils.py

The most recent changes here added a 2nd attempt at enumerating disks to work-around a particular situation we're seeing for a particular shelf in the field. The problem, is that the skip logic was inverted so the 2nd attempt actually produced 0 disks.
Because of this issue, the particular problem it set out to solve was rendered useless because the 2nd attempt should be producing MORE disks than the 1st attempt (again problem a particular shelf). This fixes that regression by removing the dict comprehension and doing a good ole fashioned for loop.
Original PR: https://github.com/truenas/py-fenced/pull/51
Jira URL: https://ixsystems.atlassian.net/browse/NAS-131395

NAS-131395 / 24.10.0 / fix subtle regression in fenced (by yocalebo)

---

fenced/main.py
fenced/utils.py

After more investigation in the field, we've discovered that libudev is a fickle mistress when it comes to reliably enumerating disks on a system. The reason why is that libudev is a database cache of hardware that the kernel sees. However, it's very trivial to trigger "rescans" of such hardware which causes the udev cache to be torn down and recreated. To fix this, I remove the logic for enumerating disks via libudev.
While I'm here, I get rid of a bunch of unnecessary and duplicate logic that doesn't provide us any benefit. A list of what has changed is as follows:
1. remove libudev disk enumeration and depend on sysfs (/sys/block)
2. remove enumerating disks from middleware entirely. This means the reserve the disks in-use by a zpool "logic" was removed as well. This logic was a …

NAS-131419 / 25.04 / greatly simplify disk enumeration in fenced

---

fenced/utils.py

Internal iSCSI ALUA targets show up in `/sys/block`, even though (by design) they do **not** properly surface.
We should not be including them in the output from `load_disks_from_sys_block`.
There are multiple ways to filter them out (e.g. check for `/dev/NAME`), but this PR checks for the existence of `dev` in the `/sys/block/NAME` directory.

NAS-131428 / 25.04 / Do not use ALUA internal disks in load_disks_from_sys_block

---

fenced/utils.py

After some more troubleshooting on customer system, we've found this does not actually work as intended and the problem still exists. Until we can get a concrete reproduction and understand the problem fully, we're going to revert these changes.
NOTE: The FT branch has already been improved significantly and this logic was removed when the improvements were made so we only need to revert for 24.10.0 proper (24.10.0-RC.1 does NOT have these changes).
Original PR: https://github.com/truenas/py-fenced/pull/57
Jira URL: https://ixsystems.atlassian.net/browse/NAS-131450

NAS-131450 / 24.04.2.3 / Revert recent work-around in fenced (it doesn't work) (by yocalebo)

---

fenced/utils.py

After some more troubleshooting on customer system, we've found this does not actually work as intended and the problem still exists. Until we can get a concrete reproduction and understand the problem fully, we're going to revert these changes.
NOTE: The FT branch has already been improved significantly and this logic was removed when the improvements were made so we only need to revert for 24.10.0 proper (24.10.0-RC.1 does NOT have these changes).

NAS-131450 / 24.10.0 / Revert recent work-around in fenced (it doesn't work)

---

fenced/utils.py

The customer that was able to reproduce the disk enumeration logic tested these changes and it fixed all the issues they had. This makes sense, because the device nodes in `/dev` don't magically disappear based on some user-space "rescan" operation (like libudev). The only way the nodes in `/dev` "disappear" is if the drive physically is removed, turned off, catastrophically fails, etc. This is dramatically simplified logic which is always a good thing.

NAS-131604 / 24.04.2.3 / fix fenced disk enumeration

---

fenced/utils.py

Automatic cherry-pick failed. Please resolve conflicts by running:
git reset --hard HEAD~1
git cherry-pick -x 3d4747dbaa4184d73f2810d5eb7c59ed89888144
If the original PR was merged via a squash, you can just cherry-pick the squashed commit:
git reset --hard HEAD~1
git cherry-pick -x bd62a593331f37ff0ce199d31639b090cfd01b11
The customer that was able to reproduce the disk enumeration logic tested these changes and it fixed all the issues they had. This makes sense, because the device nodes in `/dev` don't magically disappear based on some user-space "rescan" operation (like libudev). The only way the nodes in `/dev` "disappear" is if the drive physically is removed, turned off, catastrophically fails, etc. This is dramatically simplified logic which is always a good thing.
Original PR: …

NAS-131604 / 24.10.0 / fix fenced disk enumeration (by yocalebo)
